# Generated by Django 3.2 on 2021-08-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210727_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
    ]
